[browser]
gatherUsageStats = false

[server]
headless = true

[theme]
primaryColor       = "#0082CA"
backgroundColor    = "#001e33"
secondaryBackgroundColor = "#002841"
textColor          = "#ffffff"
font               = "sans serif"
